"""
Reads terraform output JSON from stdin, writes frontend/.env.local.
Usage: terraform output -json | python scripts/write_env.py
"""
import json
import sys
import os
from pathlib import Path

MAPPING = {
    "api_endpoint":           "VITE_API_URL",
    "ws_endpoint":            "VITE_WS_URL",
    "cognito_user_pool_id":   "VITE_COGNITO_USER_POOL_ID",
    "cognito_client_id":      "VITE_COGNITO_CLIENT_ID",
    "cloudfront_domain":      "VITE_CLOUDFRONT_URL",
}

data = json.load(sys.stdin)

env_path = Path(__file__).parent.parent / "frontend" / ".env.local"
lines = ["# Auto-generated by scripts/write_env.py — do not edit manually\n"]

for tf_key, vite_key in MAPPING.items():
    value = data.get(tf_key, {}).get("value", "")
    lines.append(f"{vite_key}={value}\n")

env_path.write_text("".join(lines))
print(f"Written {env_path}")
for tf_key, vite_key in MAPPING.items():
    value = data.get(tf_key, {}).get("value", "")
    if value:
        print(f"  {vite_key}={value}")
