resource "aws_apigatewayv2_api" "this" {
  name          = "${var.prefix}-http-api"
  protocol_type = "HTTP"

  cors_configuration {
    allow_origins = ["*"]
    allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers = ["Content-Type", "Authorization", "X-Amz-Date", "X-Api-Key", "X-Amz-Security-Token"]
    max_age       = 300
  }
}

resource "aws_apigatewayv2_stage" "default" {
  api_id      = aws_apigatewayv2_api.this.id
  name        = "$default"
  auto_deploy = true
}

# POST /parse
resource "aws_apigatewayv2_integration" "parse_cobol" {
  api_id                 = aws_apigatewayv2_api.this.id
  integration_type       = "AWS_PROXY"
  integration_uri        = var.parse_cobol_invoke_arn
  payload_format_version = "2.0"
}

resource "aws_apigatewayv2_route" "parse" {
  api_id    = aws_apigatewayv2_api.this.id
  route_key = "POST /parse"
  target    = "integrations/${aws_apigatewayv2_integration.parse_cobol.id}"
}

resource "aws_lambda_permission" "parse_cobol" {
  statement_id  = "AllowAPIGWInvoke"
  action        = "lambda:InvokeFunction"
  function_name = var.parse_cobol_function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_apigatewayv2_api.this.execution_arn}/*/*/parse"
}

# Phase 2: POST /migrate
resource "aws_apigatewayv2_integration" "trigger_migrate" {
  api_id                 = aws_apigatewayv2_api.this.id
  integration_type       = "AWS_PROXY"
  integration_uri        = var.trigger_migrate_invoke_arn
  payload_format_version = "2.0"
}

resource "aws_apigatewayv2_route" "migrate" {
  api_id    = aws_apigatewayv2_api.this.id
  route_key = "POST /migrate"
  target    = "integrations/${aws_apigatewayv2_integration.trigger_migrate.id}"
}

resource "aws_lambda_permission" "trigger_migrate" {
  statement_id  = "AllowAPIGWInvokeMigrate"
  action        = "lambda:InvokeFunction"
  function_name = var.trigger_migrate_function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_apigatewayv2_api.this.execution_arn}/*/*/migrate"
}

# Write VITE_ env vars to frontend/.env.local after every apply
resource "terraform_data" "write_env_local" {
  depends_on = [aws_apigatewayv2_stage.default]

  triggers_replace = [
    aws_apigatewayv2_api.this.api_endpoint,
    var.ws_endpoint,
  ]

  provisioner "local-exec" {
    interpreter = ["PowerShell", "-Command"]
    command     = <<-EOT
      $content = @"
# Auto-generated by Terraform — do not edit manually
VITE_API_URL=${aws_apigatewayv2_api.this.api_endpoint}
VITE_WS_URL=${var.ws_endpoint}
VITE_COGNITO_USER_POOL_ID=
VITE_COGNITO_CLIENT_ID=
"@
      [System.IO.File]::WriteAllText("${var.env_local_path}", $content, [System.Text.UTF8Encoding]::new($false))
      Write-Host "Written ${var.env_local_path}"
      Write-Host "  VITE_API_URL=${aws_apigatewayv2_api.this.api_endpoint}"
      Write-Host "  VITE_WS_URL=${var.ws_endpoint}"
    EOT
  }
}
